package cardiotrack;

import cardiotrack.Medicao;

import java.awt.List;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaInicial extends javax.swing.JFrame {
    String caminho = System.getProperty("user.home") + "\\Desktop\\medicao.csv";

    public TelaInicial() {
        initComponents();
        geraAcessibilidade();
        leMedicoesAnteriores();
    }

    public void geraAcessibilidade() {
        btnSalvar.setMnemonic(KeyEvent.VK_D);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblData = new javax.swing.JLabel();
        lblHorario = new javax.swing.JLabel();
        lblPressaoSistolica = new javax.swing.JLabel();
        lblPressaoDiastolica = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        txtPressaoSistolica = new javax.swing.JTextField();
        txtHorario = new javax.swing.JTextField();
        txtPressaoDiastolica = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        cbEstresse = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMedicoes = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("CardioTrack");
        lblTitulo.setToolTipText("Título do programa CardioTrack");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da medição realizada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N
        jLayeredPane1.setToolTipText("Insira os dados da medição realizada para salvar no arquivo");

        lblData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblData.setLabelFor(txtData);
        lblData.setText("Data:");
        lblData.setToolTipText("Data da medição no formato dd/mm/aaaa");

        lblHorario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHorario.setLabelFor(txtHorario);
        lblHorario.setText("Horário:");
        lblHorario.setToolTipText("Horário da medição no formato XX:XX");

        lblPressaoSistolica.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPressaoSistolica.setLabelFor(txtPressaoSistolica);
        lblPressaoSistolica.setText("Pressão sistólica:");
        lblPressaoSistolica.setToolTipText("Pressão sistólica no horário da medição");

        lblPressaoDiastolica.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPressaoDiastolica.setLabelFor(txtPressaoDiastolica);
        lblPressaoDiastolica.setText("Pressão diastólica:");
        lblPressaoDiastolica.setToolTipText("Pressão diastólica no horário da medição");

        txtData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtData.setToolTipText("Informe a data da medição");
        txtData.setNextFocusableComponent(txtHorario);
        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });

        txtPressaoSistolica.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPressaoSistolica.setToolTipText("Informe a pressão sistólica no horário da medição");
        txtPressaoSistolica.setNextFocusableComponent(txtPressaoDiastolica);
        txtPressaoSistolica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPressaoSistolicaActionPerformed(evt);
            }
        });

        txtHorario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtHorario.setToolTipText("Informe o horário da medição");
        txtHorario.setNextFocusableComponent(txtPressaoSistolica);
        txtHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHorarioActionPerformed(evt);
            }
        });

        txtPressaoDiastolica.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPressaoDiastolica.setToolTipText("Informe a pressão diastólica no horário da medição");
        txtPressaoDiastolica.setNextFocusableComponent(cbEstresse);
        txtPressaoDiastolica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPressaoDiastolicaActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Botão para salvar os dados");
        btnSalvar.setNextFocusableComponent(txtData);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        cbEstresse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbEstresse.setText("Está em situação de estresse");
        cbEstresse.setToolTipText("Informe se está em situação de estresse no momento da medição");
        cbEstresse.setNextFocusableComponent(btnSalvar);
        cbEstresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstresseActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(lblData, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblHorario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblPressaoSistolica, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblPressaoDiastolica, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtData, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtPressaoSistolica, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtHorario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtPressaoDiastolica, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnSalvar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cbEstresse, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
                jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                                .addComponent(lblPressaoSistolica)
                                                .addGap(30, 30, 30)
                                                .addComponent(txtPressaoSistolica, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                                        .addComponent(lblPressaoDiastolica)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txtPressaoDiastolica, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(lblHorario)
                                                                .addComponent(lblData))
                                                        .addGap(98, 98, 98)
                                                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbEstresse)
                                        .addComponent(btnSalvar))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
                jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblData)
                                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbEstresse))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblHorario)
                                        .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblPressaoSistolica)
                                        .addComponent(txtPressaoSistolica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblPressaoDiastolica)
                                        .addComponent(txtPressaoDiastolica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnSalvar))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblMedicoes.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Data", "Horário", "Pressão sistólica", "Pressão diastólica", "Situação de estresse"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblMedicoes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblTitulo)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jScrollPane2))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblTitulo)
                                .addGap(18, 18, 18)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                .addContainerGap())
        );

        jMenu1.setText("Menu");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void cbEstresseActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtPressaoSistolicaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtHorarioActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtPressaoDiastolicaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {
        String data = txtData.getText();
        String horario = txtHorario.getText();
        String pressaoSistolica = txtPressaoSistolica.getText();
        String pressaoDiastolica = txtPressaoDiastolica.getText();
        Boolean estaEstressado = cbEstresse.isSelected();

        if (verificaDados(data, horario, pressaoSistolica, pressaoDiastolica)) {
            Medicao medicao = new Medicao(data, horario, Integer.parseInt(pressaoSistolica), Integer.parseInt(pressaoDiastolica), estaEstressado);

            String dados = "\nData: " + medicao.getData()
                    + "\nHorário: " + medicao.getHorario()
                    + "\nPressão sistólica: " + medicao.getPressaoSistolica()
                    + "\nPressão diastólica: " + medicao.getPressaoDiastolica()
                    +"\nEstá em situação de estresse: " + (estaEstressado ? "Sim\n\n" : "Não\n\n");

            criaArquivo();
            registraMedicao(medicao, dados);

            limpaDados();
        }
    }

    private void leMedicoesAnteriores() {
        File arquivo = new File(caminho);

        if(!arquivo.exists()) {
            return;
        }

        try (BufferedReader br = new BufferedReader(new FileReader(caminho))) {
            DefaultTableModel tabelaModelo = (DefaultTableModel) tblMedicoes.getModel();
            tabelaModelo.setRowCount(0);

            String linha;
            boolean primeiraLinha = true;

            while ((linha = br.readLine()) != null) {
                if (primeiraLinha) {
                    primeiraLinha = false;
                    continue;
                }

                String[] valores = linha.split(";");
                tabelaModelo.addRow(valores);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro ao ler as medições anteriores.");
        }
    }

    private void registraMedicao(Medicao medicao, String dados) {
        File arquivo = new File(caminho);

        try (FileWriter csvWriter = new FileWriter(arquivo, true);
             BufferedReader br = new BufferedReader(new FileReader(arquivo))) {

            if (br.readLine() == null) {
                csvWriter.append("Data;Horário;Pressão sistólica;Pressão diastólica;Está estressado\n");
            }

            csvWriter.append(medicao.getData()).append(";");
            csvWriter.append(medicao.getHorario()).append(";");
            csvWriter.append(String.valueOf(medicao.getPressaoSistolica())).append(";");
            csvWriter.append(String.valueOf(medicao.getPressaoDiastolica())).append(";");
            csvWriter.append(medicao.isEstaEstressado() ? "Sim" : "Não").append("\n");

            JOptionPane.showMessageDialog(null, "Dados inseridos:" + dados);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu algum erro ao registrar os arquivos.");
        }

        leMedicoesAnteriores();
    }

    private void criaArquivo() {
        try {
            File arquivo = new File(caminho);
            arquivo.createNewFile();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro na criação do arquivo." + e.getMessage());
        }
    }

    private boolean verificaDados(String data, String horario, String sistolica, String diastolica) {
        if(data.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Você precisa informar a data. Use o formato dia/mês/ano (DD/MM/AAAA).");
            return false;
        } else {
            if(!data.matches("(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/\\d{4}")){
                JOptionPane.showMessageDialog(null,
                        "A data informada não é válida.\n" +
                                "Certifique-se de que:\n" +
                                "- O dia está entre 01 e 31.\n" +
                                "- O mês está entre 01 e 12.\n" +
                                "- O ano contém 4 dígitos.\n" +
                                "Exemplo válido: 15/08/2024.");
                return false;
            }
        }

        if(horario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Você precisa informar o horário. Use o formato HH:MM (24 horas).");
            return false;
        } else {
            if(!horario.matches("([01]\\d|2[0-3]):([0-5]\\d)")){
                JOptionPane.showMessageDialog(null,
                        "O horário informado não é válido.\n" +
                                "Certifique-se de que:\n" +
                                "- A hora está entre 00 e 23.\n" +
                                "- Os minutos estão entre 00 e 59.\n" +
                                "Exemplo válido: 14:30.");
                return false;
            }
        }

        if(!verificaPressao(sistolica, "sistólica") || !verificaPressao(diastolica, "diastólica")) {
            return false;
        }

        return true;
    }

    private boolean verificaPressao(String pressao, String tipoPressao) {
        if(pressao.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Você precisa informar a pressão " + tipoPressao + ".");
            return false;
        } else {
            try {
                Integer.parseInt(pressao);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "A pressão " + tipoPressao + " precisa ser um número inteiro válido.");
                return false;
            }
        }
        return true;
    }

    private void limpaDados() {
        txtData.setText("");
        txtHorario.setText("");
        txtPressaoSistolica.setText("");
        txtPressaoDiastolica.setText("");

        cbEstresse.setSelected(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox cbEstresse;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblPressaoDiastolica;
    private javax.swing.JLabel lblPressaoSistolica;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblMedicoes;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtPressaoDiastolica;
    private javax.swing.JTextField txtPressaoSistolica;
    // End of variables declaration
}
